/*
 * generated by Xtext 2.19.0
 */
package org.xtext.insa.qcm.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.insa.qcm.QcmRuntimeModule
import org.xtext.insa.qcm.QcmStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class QcmIdeSetup extends QcmStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new QcmRuntimeModule, new QcmIdeModule))
	}
	
}
